---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:

    - name: Check vector binary exists
      ansible.builtin.stat:
        path: /opt/vector/bin/vector
      register: vector_binary

    - name: Assert vector binary exists
      ansible.builtin.assert:
        that:
          - vector_binary.stat.exists
